name: Dart CI

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dart_project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.2.5'

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run tests
        run: dart test
